-- Create the main table
CREATE TABLE modified_generated_name (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255),
    task_id VARCHAR(255),
    identifier VARCHAR(255),
    generated_fully_specified_name TEXT,
    modified_fully_specified_name TEXT,
    generated_preferred_term TEXT,
    modified_preferred_term TEXT,
    name_generator_spec JSON NOT NULL,
    PRIMARY KEY (id)
);

-- Create an index on the created field for better query performance
CREATE INDEX idx_modified_generated_name_created ON modified_generated_name (created);