CREATE TABLE bulk_concept_ids
(
    id         BIGINT NOT NULL,
    concept_id BIGINT
);
CREATE TABLE bulk_concept_ids_aud
(
    rev        INTEGER NOT NULL,
    id         BIGINT  NOT NULL,
    concept_id BIGINT  NOT NULL,
    revtype    SMALLINT,
    CONSTRAINT pk_bulk_concept_ids_aud PRIMARY KEY (rev, id, concept_id)
);
CREATE TABLE bulk_product_action
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version     INTEGER,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255),
    modified    TIMESTAMP WITHOUT TIME ZONE,
    modified_by VARCHAR(255),
    ticket_id   BIGINT                                  NOT NULL,
    name        VARCHAR(2048)                           NOT NULL,
    details     JSONB                                   NOT NULL,
    CONSTRAINT pk_bulk_product_action PRIMARY KEY (id)
);
CREATE TABLE bulk_product_action_aud
(
    rev       INTEGER NOT NULL,
    revtype   SMALLINT,
    id        BIGINT  NOT NULL,
    ticket_id BIGINT,
    name      VARCHAR(2048),
    details   JSONB
);
ALTER TABLE bulk_product_action_aud
    ADD CONSTRAINT pk_bulk_product_action_aud PRIMARY KEY (rev, id);
ALTER TABLE bulk_product_action
    ADD CONSTRAINT bulk_product_name_ticket_unique UNIQUE (ticket_id, name);
ALTER TABLE bulk_product_action_aud
    ADD CONSTRAINT FK_BULK_PRODUCT_ACTION_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (rev);
ALTER TABLE bulk_product_action
    ADD CONSTRAINT FK_BULK_PRODUCT_ACTION_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES ticket (id);
ALTER TABLE bulk_concept_ids_aud
    ADD CONSTRAINT fk_bulk_concept_ids_aud_on_rev FOREIGN KEY (rev) REFERENCES revinfo (rev);
ALTER TABLE bulk_concept_ids
    ADD CONSTRAINT fk_bulk_concept_ids_on_bulk_product_action FOREIGN KEY (id) REFERENCES bulk_product_action (id);
