CREATE TABLE json_field (
    version integer,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    ticket_id BIGINT,
    value JSONB NOT NULL,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    modified TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    PRIMARY KEY (id),
    FOREIGN KEY (ticket_id) REFERENCES ticket(id),
    UNIQUE (name, ticket_id) -- Define composite unique constraint
);

-- Create audit table for JsonField entity
CREATE TABLE json_field_aud (
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    id BIGINT NOT NULL,
    name VARCHAR(255),
    ticket_id BIGINT,
    value JSONB,
    created TIMESTAMP WITH TIME ZONE,
    modified TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    PRIMARY KEY (rev, id)
);