create table external_requestor (version integer, created timestamp(6) with time zone not null, id bigint generated by default as identity, modified timestamp(6) with time zone, created_by varchar(255), description varchar(255), display_color varchar(255), modified_by varchar(255), name varchar(255) unique, primary key (id));
create table external_requestor_aud (rev integer not null, revtype smallint, id bigint not null, description varchar(255), display_color varchar(255), name varchar(255), primary key (rev, id));

create table ticket_external_requestors (external_requestor_id bigint not null, ticket_id bigint not null);
create table ticket_external_requestors_aud (rev integer not null, revtype smallint, external_requestor_id bigint not null, ticket_id bigint not null, primary key (rev, external_requestor_id, ticket_id));


alter table if exists ticket_external_requestors add constraint fk_external_requestor foreign key (external_requestor_id) references external_requestor;
alter table if exists ticket_external_requestors add constraint fk_external_requestor_ticket foreign key (ticket_id) references ticket;
alter table if exists ticket_external_requestors_aud add constraint fk_external_requestor_aud foreign key (rev) references revinfo;
alter table if exists ticket_external_requestors_aud add constraint fk_external_requestor_ticket_aud foreign key (rev) references revinfo;