CREATE TABLE job_results (
version integer,
id BIGINT GENERATED BY DEFAULT AS IDENTITY,
finished_time TIMESTAMP WITH TIME ZONE NOT NULL,
job_name VARCHAR(255),
job_id VARCHAR(255),
acknowledged boolean,
results JSONB NOT NULL,
created TIMESTAMP WITH TIME ZONE NOT NULL,
modified TIMESTAMP WITH TIME ZONE,
created_by VARCHAR(255),
modified_by VARCHAR(255),
PRIMARY KEY (id),
UNIQUE (job_id)
);

CREATE TABLE job_results_aud (
rev INTEGER NOT NULL,
revtype SMALLINT,
id BIGINT NOT NULL,
job_name VARCHAR(255),
job_id VARCHAR(255),
acknowledged boolean,
finished_time TIMESTAMP WITH TIME ZONE NOT NULL,
results JSONB,
created TIMESTAMP WITH TIME ZONE,
modified TIMESTAMP WITH TIME ZONE,
created_by VARCHAR(255),
modified_by VARCHAR(255),
PRIMARY KEY (rev, id)
);