-- Migration for ExternalProcess table
CREATE TABLE external_process (
    version integer,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    process_name VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    modified TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    PRIMARY KEY (id)
);

-- Migration for ExternalProcess audit table (external_process_aud)
CREATE TABLE external_process_aud (
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    id BIGINT NOT NULL,
    process_name VARCHAR(255),
    enabled BOOLEAN,
    created TIMESTAMP WITH TIME ZONE,
    modified TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    PRIMARY KEY (id, rev)
);