-- Migration for SynonymConfiguration table
CREATE TABLE synonym_configuration (
    version integer,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    search_string VARCHAR(255) NOT NULL,
    replacement_string VARCHAR(255) NOT NULL,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    modified TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    PRIMARY KEY (id)
);

-- Migration for SynonymConfiguration audit table (synonym_configuration_aud)
CREATE TABLE synonym_configuration_aud (
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    id BIGINT NOT NULL,
    search_string VARCHAR(255),
    replacement_string VARCHAR(255),
    created TIMESTAMP WITH TIME ZONE,
    modified TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR(255),
    modified_by VARCHAR(255),
    PRIMARY KEY (id, rev)
);