-- Promote ticket_external_requestors from a pure join table to a full entity
-- by adding a surrogate PK, BaseAuditableEntity columns, and a user-editable date_requested.

-- Add surrogate PK and auditable columns to main table
ALTER TABLE ticket_external_requestors ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE ticket_external_requestors ADD COLUMN version INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE ticket_external_requestors ADD COLUMN created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE ticket_external_requestors ADD COLUMN created_by VARCHAR(255);
ALTER TABLE ticket_external_requestors ADD COLUMN modified TIMESTAMP WITH TIME ZONE;
ALTER TABLE ticket_external_requestors ADD COLUMN modified_by VARCHAR(255);
ALTER TABLE ticket_external_requestors ADD COLUMN date_requested DATE;

-- Set id values for existing rows (sequence already assigned them above via IDENTITY, but we need a PK)
ALTER TABLE ticket_external_requestors ADD CONSTRAINT pk_ticket_external_requestors PRIMARY KEY (id);

-- Enforce uniqueness on the natural key (previously implicit from the compound-only table)
ALTER TABLE ticket_external_requestors ADD CONSTRAINT uq_ticket_external_requestors UNIQUE (ticket_id, external_requestor_id);

-- Migrate audit table to match new entity structure (PK becomes (rev, id))
ALTER TABLE ticket_external_requestors_aud ADD COLUMN id BIGINT;
ALTER TABLE ticket_external_requestors_aud ADD COLUMN date_requested DATE;

-- Populate id for aud rows whose association still exists in the main table
UPDATE ticket_external_requestors_aud a
    SET id = m.id
    FROM ticket_external_requestors m
    WHERE a.ticket_id = m.ticket_id
      AND a.external_requestor_id = m.external_requestor_id;

-- Assign synthetic negative ids to orphaned aud rows (revtype=2 DELETE entries with no main-table match)
WITH ranked AS (
    SELECT ctid,
           ROW_NUMBER() OVER (ORDER BY rev, external_requestor_id, ticket_id) AS rn
    FROM ticket_external_requestors_aud
    WHERE id IS NULL
)
UPDATE ticket_external_requestors_aud t
    SET id = -r.rn
    FROM ranked r
    WHERE t.ctid = r.ctid;

ALTER TABLE ticket_external_requestors_aud DROP CONSTRAINT ticket_external_requestors_aud_pkey;
ALTER TABLE ticket_external_requestors_aud ADD CONSTRAINT pk_ticket_external_requestors_aud PRIMARY KEY (rev, id);

-- The old PK included external_requestor_id and ticket_id, so they were implicitly NOT NULL.
-- After the PK change to (rev, id), Envers DELETE records (revtype=2) insert NULL for these FK
-- columns — which violates the original column constraint. Drop the constraint.
ALTER TABLE ticket_external_requestors_aud ALTER COLUMN external_requestor_id DROP NOT NULL;
ALTER TABLE ticket_external_requestors_aud ALTER COLUMN ticket_id DROP NOT NULL;
