create table schedule (grouping integer, version integer, created timestamp(6) with time zone not null, id bigint generated by default as identity, modified timestamp(6) with time zone, created_by varchar(255), description varchar(255), name varchar(255) unique, modified_by varchar(255), primary key (id));
create table schedule_aud (grouping integer, rev integer not null, revtype smallint, id bigint not null, description varchar(255), name varchar(255), primary key (rev, id));

alter table ticket add column schedule_id bigint;
alter table ticket_aud add column schedule_id bigint;