{{- if $.Values.snomio.telemetry.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Release.Name }}-java-instrumentation
  labels:
    app: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  exporter:
    endpoint: "http://{{ .Release.Name }}-collector:9411"
    exporter: "zipkin"
  java:
    image: otel/autoinstrumentation-java:latest
    env:
      - name: OTEL_TRACES_EXPORTER
        value: "zipkin"
      - name: OTEL_SERVICE_NAME
        value: "{{ .Release.Name }}/{{ .Release.Name }}"
      - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
        value: "http://{{ .Release.Name }}-collector:9411"
      - name: OTEL_METRICS_EXPORTER
        value: "none"
      - name: OTEL_LOGS_EXPORTER
        value: "none"
      - name: OTEL_PROPAGATORS
        value: "tracecontext,baggage,b3"
      - name: OTEL_INSTRUMENTATION_COMMON_ENDUSER_ENABLED
        value: "true"
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
 name: {{ .Release.Name }}
 labels:
   app: opentelemetry
   component: otel-operator
spec:
  config: |
   receivers:
     zipkin:
       endpoint: 0.0.0.0:9411
     otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
   propagators:
    - tracecontext
    - baggage
    - b3
   processors:
     memory_limiter:
       check_interval: 1s
       limit_percentage: 75
       spike_limit_percentage: 15
     batch:
       send_batch_size: 1000
       timeout: 0s
   exporters:
     logging:
       loglevel: debug
     otlp:
       endpoint: tempo-distributor.monitoring.svc.cluster.local:4317
       tls:
         insecure: true
     zipkin:
       endpoint: "http://tempo-distributor.monitoring.svc.cluster.local:9411"
       tls:
         insecure: true
   service:
     pipelines:
       traces:
         receivers: [otlp,zipkin]
         processors: [memory_limiter, batch]
         exporters: [zipkin,otlp,logging]
{{- end }}