import { ConceptDetails, Product } from '../types/concept';

const tempNewConcept = {
  concept: null,
  conceptOptions: [],
  label: 'CTPP',
  newConceptDetails: {
    conceptId: -4,
    specifiedConceptId: null,
    fullySpecifiedName:
      'testclinton (containerized branded clinical drug package)',
    preferredTerm: 'Amoxil 250 mg capsule, 21, blister pack',
    semanticTag: 'containerized branded clinical drug package',
    axioms: [
      {
        axiomId: null,
        moduleId: '32506021000036107',
        active: true,
        released: false,
        definitionStatusId: '900000000000073002',
        relationships: [
          {
            internalId: null,
            path: null,
            start: null,
            end: null,
            deleted: null,
            changed: null,
            active: true,
            moduleId: '32506021000036107',
            effectiveTimeI: null,
            released: false,
            releaseHash: null,
            releasedEffectiveTime: null,
            relationshipId: null,
            sourceId: null,
            destinationId: '6100011000036109',
            value: null,
            concreteValue: null,
            relationshipGroup: 1,
            typeId: '774160008',
            characteristicTypeId: '900000000000010007',
            modifierId: '900000000000450001',
            source: null,
            type: {
              conceptId: '774160008',
              active: true,
              definitionStatus: 'PRIMITIVE',
              moduleId: null,
              effectiveTime: null,
              fsn: {
                term: 'Contains clinical drug (attribute)',
                lang: 'en',
              },
              pt: {
                term: 'Contains clinical drug',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: '774160008',
              definitionStatusId: '900000000000074008',
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm: null,
            },
            target: {
              conceptId: '6100011000036109',
              active: true,
              definitionStatus: 'FULLY_DEFINED',
              moduleId: '32506021000036107',
              effectiveTime: '20240131',
              fsn: {
                term: 'Amoxil (amoxicillin 250 mg) capsule (branded clinical drug)',
                lang: 'en',
              },
              pt: {
                term: 'Amoxil 250 mg capsule',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: '6100011000036109',
              definitionStatusId: null,
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm:
                '6100011000036109 | Amoxil (amoxicillin 250 mg) capsule (branded clinical drug) |',
            },
            characteristicType: '900000000000010007',
            groupId: 1,
            grouped: true,
            inferred: false,
            relationshipIdAsLong: null,
            modifier: 'EXISTENTIAL',
            concrete: false,
            effectiveTime: null,
            id: null,
          },
          {
            internalId: null,
            path: null,
            start: null,
            end: null,
            deleted: null,
            changed: null,
            active: true,
            moduleId: '32506021000036107',
            effectiveTimeI: null,
            released: false,
            releaseHash: null,
            releasedEffectiveTime: null,
            relationshipId: null,
            sourceId: null,
            destinationId: null,
            value: null,
            concreteValue: {
              dataType: 'INTEGER',
              value: '1',
              valueWithPrefix: '#1',
            },
            relationshipGroup: 1,
            typeId: '999000131000168101',
            characteristicTypeId: '900000000000010007',
            modifierId: '900000000000450001',
            source: null,
            type: {
              conceptId: '999000131000168101',
              active: true,
              definitionStatus: 'PRIMITIVE',
              moduleId: null,
              effectiveTime: null,
              fsn: {
                term: 'Count of contained component ingredient (attribute)',
                lang: 'en',
              },
              pt: {
                term: 'Count of contained component ingredient',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: '999000131000168101',
              definitionStatusId: '900000000000074008',
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm: null,
            },
            target: null,
            characteristicType: '900000000000010007',
            groupId: 1,
            grouped: true,
            inferred: false,
            relationshipIdAsLong: null,
            modifier: 'EXISTENTIAL',
            concrete: true,
            effectiveTime: null,
            id: null,
          },
          {
            internalId: null,
            path: null,
            start: null,
            end: null,
            deleted: null,
            changed: null,
            active: true,
            moduleId: '32506021000036107',
            effectiveTimeI: null,
            released: false,
            releaseHash: null,
            releasedEffectiveTime: null,
            relationshipId: null,
            sourceId: null,
            destinationId: null,
            value: null,
            concreteValue: {
              dataType: 'DECIMAL',
              value: '21',
              valueWithPrefix: '#21',
            },
            relationshipGroup: 1,
            typeId: '1142142004',
            characteristicTypeId: '900000000000010007',
            modifierId: '900000000000450001',
            source: null,
            type: {
              conceptId: '1142142004',
              active: true,
              definitionStatus: 'PRIMITIVE',
              moduleId: null,
              effectiveTime: null,
              fsn: {
                term: 'Has pack size (attribute)',
                lang: 'en',
              },
              pt: {
                term: 'Has pack size',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: '1142142004',
              definitionStatusId: '900000000000074008',
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm: null,
            },
            target: null,
            characteristicType: '900000000000010007',
            groupId: 1,
            grouped: true,
            inferred: false,
            relationshipIdAsLong: null,
            modifier: 'EXISTENTIAL',
            concrete: true,
            effectiveTime: null,
            id: null,
          },
          {
            internalId: null,
            path: null,
            start: null,
            end: null,
            deleted: null,
            changed: null,
            active: true,
            moduleId: '32506021000036107',
            effectiveTimeI: null,
            released: false,
            releaseHash: null,
            releasedEffectiveTime: null,
            relationshipId: null,
            sourceId: null,
            destinationId: '287011000036106',
            value: null,
            concreteValue: null,
            relationshipGroup: 0,
            typeId: '30465011000036106',
            characteristicTypeId: '900000000000010007',
            modifierId: '900000000000450001',
            source: null,
            type: {
              conceptId: '30465011000036106',
              active: true,
              definitionStatus: 'PRIMITIVE',
              moduleId: null,
              effectiveTime: null,
              fsn: {
                term: 'has container type (relationship type)',
                lang: 'en',
              },
              pt: {
                term: 'has container type',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: '30465011000036106',
              definitionStatusId: '900000000000074008',
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm: null,
            },
            target: {
              conceptId: '287011000036106',
              active: true,
              definitionStatus: 'PRIMITIVE',
              moduleId: '32506021000036107',
              effectiveTime: null,
              fsn: {
                term: 'Blister pack (physical object)',
                lang: 'en',
              },
              pt: {
                term: 'Blister pack',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: '287011000036106',
              definitionStatusId: null,
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm:
                '287011000036106 | Blister pack (physical object) |',
            },
            characteristicType: '900000000000010007',
            groupId: 0,
            grouped: false,
            inferred: false,
            relationshipIdAsLong: null,
            modifier: 'EXISTENTIAL',
            concrete: false,
            effectiveTime: null,
            id: null,
          },
          {
            internalId: null,
            path: null,
            start: null,
            end: null,
            deleted: null,
            changed: null,
            active: true,
            moduleId: '32506021000036107',
            effectiveTimeI: null,
            released: false,
            releaseHash: null,
            releasedEffectiveTime: null,
            relationshipId: null,
            sourceId: null,
            destinationId: '781405001',
            value: null,
            concreteValue: null,
            relationshipGroup: 0,
            typeId: '116680003',
            characteristicTypeId: '900000000000010007',
            modifierId: '900000000000450001',
            source: null,
            type: {
              conceptId: '116680003',
              active: true,
              definitionStatus: 'PRIMITIVE',
              moduleId: null,
              effectiveTime: null,
              fsn: {
                term: 'Is a (attribute)',
                lang: 'en',
              },
              pt: {
                term: 'Is a',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: '116680003',
              definitionStatusId: '900000000000074008',
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm: null,
            },
            target: {
              conceptId: '781405001',
              active: true,
              definitionStatus: 'PRIMITIVE',
              moduleId: null,
              effectiveTime: null,
              fsn: {
                term: 'Medicinal product package (product)',
                lang: 'en',
              },
              pt: {
                term: 'Medicinal product package',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: '781405001',
              definitionStatusId: '900000000000074008',
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm: null,
            },
            characteristicType: '900000000000010007',
            groupId: 0,
            grouped: false,
            inferred: false,
            relationshipIdAsLong: null,
            modifier: 'EXISTENTIAL',
            concrete: false,
            effectiveTime: null,
            id: null,
          },
          {
            internalId: null,
            path: null,
            start: null,
            end: null,
            deleted: null,
            changed: null,
            active: true,
            moduleId: '32506021000036107',
            effectiveTimeI: null,
            released: false,
            releaseHash: null,
            releasedEffectiveTime: null,
            relationshipId: null,
            sourceId: null,
            destinationId: '-3',
            value: null,
            concreteValue: null,
            relationshipGroup: 0,
            typeId: '116680003',
            characteristicTypeId: '900000000000010007',
            modifierId: '900000000000450001',
            source: null,
            type: {
              conceptId: '116680003',
              active: true,
              definitionStatus: 'PRIMITIVE',
              moduleId: null,
              effectiveTime: null,
              fsn: {
                term: 'Is a (attribute)',
                lang: 'en',
              },
              pt: {
                term: 'Is a',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: '116680003',
              definitionStatusId: '900000000000074008',
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm: null,
            },
            target: {
              conceptId: '-3',
              active: true,
              definitionStatus: 'FULLY_DEFINED',
              moduleId: '32506021000036107',
              effectiveTime: null,
              fsn: {
                term: 'Amoxil (amoxicillin 250 mg) capsule, 21 capsules (branded clinical drug package)',
                lang: 'en',
              },
              pt: {
                term: 'Amoxil 250 mg capsule, 21',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: null,
              definitionStatusId: 'FULLY_DEFINED',
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm: null,
            },
            characteristicType: '900000000000010007',
            groupId: 0,
            grouped: false,
            inferred: false,
            relationshipIdAsLong: null,
            modifier: 'EXISTENTIAL',
            concrete: false,
            effectiveTime: null,
            id: null,
          },
          {
            internalId: null,
            path: null,
            start: null,
            end: null,
            deleted: null,
            changed: null,
            active: true,
            moduleId: '32506021000036107',
            effectiveTimeI: null,
            released: false,
            releaseHash: null,
            releasedEffectiveTime: null,
            relationshipId: null,
            sourceId: null,
            destinationId: '732935002',
            value: null,
            concreteValue: null,
            relationshipGroup: 1,
            typeId: '774163005',
            characteristicTypeId: '900000000000010007',
            modifierId: '900000000000450001',
            source: null,
            type: {
              conceptId: '774163005',
              active: true,
              definitionStatus: 'PRIMITIVE',
              moduleId: null,
              effectiveTime: null,
              fsn: {
                term: 'Has pack size unit (attribute)',
                lang: 'en',
              },
              pt: {
                term: 'Has pack size unit',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              // "isLeafStated": null,
              id: '774163005',
              // "definitionStatusId": "900000000000074008",
              // "leafInferred": null,
              // "leafStated": null,
              // "extraFields": {},
              idAndFsnTerm: null,
            },
            target: {
              conceptId: '732935002',
              active: true,
              definitionStatus: 'PRIMITIVE',
              moduleId: '900000000000207008',
              effectiveTime: null,
              fsn: {
                term: 'Unit of presentation (unit of presentation)',
                lang: 'en',
              },
              pt: {
                term: 'Each',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: '732935002',
              definitionStatusId: null,
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm:
                '732935002 | Unit of presentation (unit of presentation) |',
            },
            characteristicType: '900000000000010007',
            groupId: 1,
            grouped: true,
            inferred: false,
            relationshipIdAsLong: null,
            modifier: 'EXISTENTIAL',
            concrete: false,
            effectiveTime: null,
            id: null,
          },
          {
            internalId: null,
            path: null,
            start: null,
            end: null,
            deleted: null,
            changed: null,
            active: true,
            moduleId: '32506021000036107',
            effectiveTimeI: null,
            released: false,
            releaseHash: null,
            releasedEffectiveTime: null,
            relationshipId: null,
            sourceId: null,
            destinationId: '3738011000036101',
            value: null,
            concreteValue: null,
            relationshipGroup: 0,
            typeId: '774158006',
            characteristicTypeId: '900000000000010007',
            modifierId: '900000000000450001',
            source: null,
            type: {
              conceptId: '774158006',
              active: true,
              definitionStatus: 'PRIMITIVE',
              moduleId: null,
              effectiveTime: null,
              fsn: {
                term: 'Has product name (attribute)',
                lang: 'en',
              },
              pt: {
                term: 'Has product name',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: '774158006',
              definitionStatusId: '900000000000074008',
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm: null,
            },
            target: {
              conceptId: '3738011000036101',
              active: true,
              definitionStatus: 'PRIMITIVE',
              moduleId: '32506021000036107',
              effectiveTime: null,
              fsn: {
                term: 'Amoxil (product name)',
                lang: 'en',
              },
              pt: {
                term: 'Amoxil',
                lang: 'en',
              },
              descendantCount: null,
              isLeafInferred: null,
              isLeafStated: null,
              id: '3738011000036101',
              definitionStatusId: null,
              leafInferred: null,
              leafStated: null,
              extraFields: {},
              idAndFsnTerm: '3738011000036101 | Amoxil (product name) |',
            },
            characteristicType: '900000000000010007',
            groupId: 0,
            grouped: false,
            inferred: false,
            relationshipIdAsLong: null,
            modifier: 'EXISTENTIAL',
            concrete: false,
            effectiveTime: null,
            id: null,
          },
        ],
        definitionStatus: 'FULLY_DEFINED',
        id: null,
        effectiveTime: null,
      },
    ],
    referenceSetMembers: [
      {
        releasedEffectiveTime: null,
        referencedComponentId: null,
        memberId: null,
        effectiveTime: null,
        refsetId: '11000168105',
        released: null,
        moduleId: '32506021000036107',
        additionalFields: {
          mapTarget: '273935',
        },
        active: true,
      },
      {
        releasedEffectiveTime: null,
        referencedComponentId: null,
        memberId: null,
        effectiveTime: null,
        refsetId: '11000168105',
        released: null,
        moduleId: '32506021000036107',
        additionalFields: {
          mapTarget: '56550',
        },
        active: true,
      },
    ],
    active: true,
    definitionStatus: 'FULLY_DEFINED',
    moduleId: '32506021000036107',
    fsn: {
      term: 'Amoxil (amoxicillin 250 mg) capsule, 21 capsules, blister pack (containerized branded clinical drug package)',
      lang: 'en',
    },
    pt: {
      term: 'Amoxil 250 mg capsule, 21, blister pack',
      lang: 'en',
    },
    released: false,
  },
  conceptId: '-4',
  preferredTerm: 'Amoxil 250 mg capsule, 21, blister pack',
  newConcept: true,
  idAndFsnTerm:
    '-4| Amoxil (amoxicillin 250 mg) capsule, 21 capsules, blister pack (containerized branded clinical drug package)|',
  fullySpecifiedName:
    'Amoxil (amoxicillin 250 mg) capsule, 21 capsules, blister pack (containerized branded clinical drug package)',
} as Product;

export default tempNewConcept;
