snomio:
  image: nctsacr.azurecr.io/snomio:latest
  hostNames:
    - snomio-dev.australiaeast.cloudapp.azure.com
    - dev-snomio.ihtsdotools.org
  snowstorm:
    host: dev-au-authoring.ihtsdotools.org
    apiPath: /snowstorm/snomed-ct
    defaultBranch: MAIN/SNOMEDCT-AU/AUAMT
  attachments:
    store:
      shareName: snomio-dev-attachments
  telemetry:
    enabled: true
  prometheus:
    enabled: true
  config:
    spring.flyway.baseline-on-migrate: true
    spring.application.name: snomio-dev
    spring.datasource.url: jdbc:postgresql://ncts-db.postgres.database.azure.com/snomio_dev
    ihtsdo.ap.api.url: https://dev-snowstorm.ihtsdotools.org/authoring-services
    ihtsdo.ims.api.url: https://dev-ims.ihtsdotools.org
    ihtsdo.ims.api.cookie.name: dev-ims-ihtsdo
    security.enable-csrf: "false"
    ihtsdo.ap.projectKey: AUAMT
    ihtsdo.ims.api.cookie.value: ""
    ihtsdo.base.api.url: https://dev-snowstorm.ihtsdotools.org
    ihtsdo.snowstorm.api.url: https://dev-au-authoring.ihtsdotools.org/snowstorm/snomed-ct
    caching.spring.usersTTL: "3600000"
    logging.level.com.csiro.snomio.service.SnowstormClient: DEBUG
  tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/azure-dns-label-name: snomio-dev
      name: snomio-nginx-dev
      controllerValue: 'k8s.io/snomio-nginx-dev'
    ingressClass: 'snomio-nginx-dev'

ingress:
  class: snomio-nginx-dev
