snomio:
  image: nctsacr.azurecr.io/snomio:latest
  hostNames:
    - snomio-uat.australiaeast.cloudapp.azure.com
    - uat-snomio.ihtsdotools.org
  snowstorm:
    host: uat-snowstorm.ihtsdotools.org
    apiPath: /snowstorm/snomed-ct
    defaultBranch: MAIN/SNOMEDCT-AU/AUAMT
  attachments:
    store:
      shareName: snomio-uat-attachments
      shareName: snomio-dev-attachments
  telemetry:
    enabled: true
  prometheus:
    enabled: true
  config:
    spring.flyway.baseline-on-migrate: true
    spring.application.name: snomio-uat
    spring.datasource.url: jdbc:postgresql://ncts-db.postgres.database.azure.com/snomio_uat
    ihtsdo.ap.api.url: https://uat-snowstorm.ihtsdotools.org/authoring-services
    ihtsdo.ims.api.url: https://uat-ims.ihtsdotools.org
    ihtsdo.ims.api.cookie.name: uat-ims-ihtsdo
    security.enable-csrf: "false"
    ihtsdo.ap.projectKey: AUAMT
    ihtsdo.ims.api.cookie.value: ""
    ihtsdo.base.api.url: https://uat-snowstorm.ihtsdotools.org
    ihtsdo.snowstorm.api.url: https://uat-snowstorm.ihtsdotools.org/snowstorm/snomed-ct
    caching.spring.usersTTL: "3600000"
  tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"

nginx-ingress:
  nameOverride: snomio-uat
  controller:
    pod:
      extraLabels:
        app: snomio-uat
    service:
      annotations:
        service.beta.kubernetes.io/azure-dns-label-name: snomio-uat
      name: snomio-nginx-uat
      controllerValue: 'k8s.io/snomio-nginx-uat'
    ingressClass: 'snomio-nginx-uat'
    #config:
      #entries:

ingress:
  class: snomio-nginx-uat
#  Uncomment these to use a self signed cert instead of cert-manager
#  tlsSecretName: snomio-uat-selfsigned-tls
#
#certmanager:
#  enabled: false