## Default values for snomio.

snomio:
  # image: [Docker repository for image]
  hostNames: # List of [host names] for ingress
  resources:
    cpu: 500m
    memory: 7Gi
    # these defaults result in a memory limit of 1Gi being set which Jib picks up and sets as max heap at runtime
    initialHeapSize: 4g
    maxHeapSize: 6g
    memorylimit: true
  tolerations: false
  highPriority: false
  snowstorm:
    host:
    apiPath: # Snbowstorm Snomed CT path for the full API URL (e.g: /snowstorm/snomed-ct)
    defaultBranch: # AMT Default branch (e.g: MAIN/SNOMEDCT-AU/AUAMT)
  ims:
    password: password
  database:
    password: password
  attachments:
    mountPath: /opt/data
    store:
      secretName: fileshare-secret
      shareName: supply # Set it for each Environment
      azaccountname: nctsdevstorage
      azaccountkey: supply # Supply on command line
  telemetry:
    enabled: false
  prometheus:
    enabled: false
  config:
    # This section is for server configuration via environment variables
    ap.api.url:    # Authoring platform URL (e.g: https://uat-snowstorm.ihtsdotools.org/authoring-services)
    ims.api.url:   # IHTSDO IMS url for authentication  (e.g: https://uat-ims.ihtsdotools.org)
    ims.api.cookie.name: # IMS Cookie name for auth (e.g: uat-ims-ihtsdo)
    spring.profiles.active: default

nginx-ingress:
  controller:
    enableSnippets: true
    enableCertManager: true
    ingressClassResource:
      name: snomio-nginx
      controllerValue: 'k8s.io/snomio-nginx'
      enabled: true
    service:
      annotations:
        service.beta.kubernetes.io/azure-dns-label-name: snomio
    ingressClass: 'snomio-nginx'
    ingressClassByName: true
    config:
      # We don't need this anymore as we are creating the configmap in the ingress.yaml file
      #entries:
        #log-format: or other settings as per https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/

ingress:
  tlsSecretName: snomio-tls-secret
  class: snomio-nginx
  nginx:
    sslRedirect: true

certmanager:
  enabled: true

repoSecret:
  enabled: false